spring:
  application:
    name: Lead
    
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/sakila
    username: dkassa
    password: Mysql515
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    
  config:
    
    import: optional:ConfigServer:http://localhost:8181
    
    
     
        
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


  
resilience4j:
  circuitBreaker:
    instances: 
        Lead:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            
            
            
management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always   
      
server:
  port: 8089
    